### ISSUE TITLE
Edit Item submission causes internal server error

### ISSUE THREAD

**Issue by goosinator868** [goosinator868/propbox#111]
Traceback (most recent call last):
  File "/Users/syoung/Downloads/google-cloud-sdk/platform/google_appengine/lib/webapp2-2.5.2/webapp2.py", line 1535, in __call__
    rv = self.handle_exception(request, response, e)
  File "/Users/syoung/Downloads/google-cloud-sdk/platform/google_appengine/lib/webapp2-2.5.2/webapp2.py", line 1529, in __call__
    rv = self.router.dispatch(request, response)
  File "/Users/syoung/Downloads/google-cloud-sdk/platform/google_appengine/lib/webapp2-2.5.2/webapp2.py", line 1278, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/Users/syoung/Downloads/google-cloud-sdk/platform/google_appengine/lib/webapp2-2.5.2/webapp2.py", line 1102, in __call__
    return handler.dispatch()
  File "/Users/syoung/Downloads/google-cloud-sdk/platform/google_appengine/lib/webapp2-2.5.2/webapp2.py", line 572, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/Users/syoung/Downloads/google-cloud-sdk/platform/google_appengine/lib/webapp2-2.5.2/webapp2.py", line 570, in dispatch
    return method(*args, **kwargs)
  File "/Users/syoung/Documents/2017 Fall/CS 3312/propbox/auth.py", line 103, in _decorator
    handler(_self, *args, **kwargs)
  File "/Users/syoung/Documents/2017 Fall/CS 3312/propbox/main.py", line 186, in post
    old_item_key = ndb.Key(urlsafe=self.request.get('old_item_key'))
  File "/Users/syoung/Downloads/google-cloud-sdk/platform/google_appengine/google/appengine/ext/ndb/key.py", line 230, in __new__
    self.__namespace) = self._parse_from_ref(cls, **kwargs)
  File "/Users/syoung/Downloads/google-cloud-sdk/platform/google_appengine/google/appengine/ext/ndb/key.py", line 313, in _parse_from_ref
    raise TypeError('Cannot construct Key reference from incompatible '
TypeError: Cannot construct Key reference from incompatible keyword arguments.

**Comment by hvpeteet** [comment]
I deleted a line when adding check-in/out. This has now been added back on hp-master and master
